{
 "title": "Overmind",
 "tags": [ "screeps" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "User", "query": "screeps.*" },
   { "name": "colonies", "label": "Colonies", "query": "screeps.$User.colonies.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(screeps.$User.cpu.getUsed, #B)",
     "targetFull": "asPercent(screeps.$User.cpu.getUsed, screeps.$User.cpu.limit)"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.$User.cpu.bucket" }
   ]
  },
  {
   "title": "CPU / Bucket / Resets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$User.cpu.getUsed, 'CPU')"
    },
    {
     "target": "alias(screeps.$User.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(movingAverage(screeps.$User.cpu.getUsed, '5min'), 'Average CPU')"
    },
    {
     "target": "alias(screeps.$User.cpu.limit, 'Limit')"
    },
    {
     "target": "alias(scale(derivative(screeps.$User.persistent.lastGlobalReset), 10000), 'Global Reset')"
    },
    {
     "target": "alias(scale(derivative(screeps.$User.persistent.lastMemoryReset), 10000), 'Memory Reset')"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.$User.cpu.bucket" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "target": "screeps.$User.memory.used" }
   ]
  },
  {
   "title": "IVM Heap Statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude(keepLastValue(screeps.$User.cpu.heapStatistics.*, 500), 'does_zap_garbage'), 4)"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(screeps.$User.gcl.progress, #B)",
     "targetFull": "asPercent(screeps.$User.gcl.progress, screeps.$User.gcl.progressTotal)"
    }
   ]
  },
  {
   "title": "Expansion Ranking",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.$User.leaderboard.rank" }
   ]
  },
  {
   "title": "GCL Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress, 100)), 10), 86400), 'GCL / 24hr')"
    },
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress, 100)), 500), 86400), 'GCL / 24hr (avg)')"
    }
   ]
  },
  {
   "title": "GCL by Colony",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(screeps.$User.colonies.$colonies.rcl.progress, 100)), 3600), 86400)), 3)"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 17 },
   "format": "d",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Rem')",
     "targetFull": "alias(divideSeries(alias(keepLastValue(diffSeries(screeps.$User.gcl.progressTotal, screeps.$User.gcl.progress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress)), 500), 86400), 'GCL / 24hr (avg)')), 'Rem')"
    }
   ]
  },
  { "title": "Colonies Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "rooms" },
  {
   "title": "DEFCON Levels",
   "type": "table",
   "gridPos": { "h": 21, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(screeps.$User.colonies.*.defcon), 3)"
    }
   ]
  },
  {
   "title": "Hatchery Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 22 },
   "format": "short",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.$User.colonies.$colonies.hatchery.uptime), 3)"
    }
   ]
  },
  {
   "title": "RCL Progress Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(movingAverage(perSecond(keepLastValue(screeps.$User.colonies.$colonies.rcl.progress)), 200), 86400), 3)"
    }
   ]
  },
  {
   "title": "Lab uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(screeps.$User.colonies.$colonies.evolutionChamber.avgUsage, 500), '1hour'), 3)"
    }
   ]
  },
  {
   "title": "Average Barrier Hits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.$User.colonies.*.avgBarrierHits, 100), 3)"
    }
   ]
  },
  {
   "title": "Energy Assets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.$User.colonies.$colonies.assets.energy, 100), 3)"
    }
   ]
  },
  {
   "title": "Average MiningSite Usage/Downtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(movingAverage(keepLastValue(screeps.$User.colonies.$colonies.miningSites.avgUsage), '30min'), 3), '(.*)', 'Usage - \\1')"
    },
    {
     "target": "aliasSub(aliasByNode(keepLastValue(screeps.$User.colonies.$colonies.miningSites.avgDowntime), 3), \"(.*)\", \"Downtime - \\1\")"
    }
   ]
  },
  {
   "title": "Energy Income Per Tick",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(keepLastValue(screeps.$User.colonies.$colonies.miningSites.energyInPerTick, 500), '30min'), 3)"
    }
   ]
  },
  { "title": "Terminal Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Global Mineral Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByNode(#A, 0), \"energy\")",
     "targetFull": "exclude(aliasByNode(groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.*, 500), \"sum\", 5), 0), \"energy\")"
    }
   ]
  },
  {
   "title": "Global T3 Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XGH2O, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XGHO2, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XKH2O, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XKHO2, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XLH2O, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XLHO2, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XUH2O, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XUHO2, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XZH2O, 500), 'sum', 5)"
    },
    {
     "target": "groupByNodes(keepLastValue(screeps.$User.colonies.*.assets.XZHO2, 500), 'sum', 5)"
    }
   ]
  },
  {
   "title": "Compound Production/Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(derivative(exclude(#A, '^(energy|H|O|U|K|L|Z|X)$')), '2hour'), 0)",
     "targetFull": "aliasByNode(movingAverage(derivative(exclude(groupByNodes(removeBelowValue(keepLastValue(screeps.$User.colonies.*.assets.*, 500), 0), \"sum\", 5), '^(energy|H|O|U|K|L|Z|X)$')), '2hour'), 0)"
    }
   ]
  },
  {
   "title": "Energy Transfer Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 500)"
    }
   ]
  },
  {
   "title": "Incoming Energy Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 52 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), '24hour'), 86000)), 0)"
    }
   ]
  },
  {
   "title": "Incoming Energy per 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), 500), 86000), 0)"
    }
   ]
  },
  {
   "title": "Fractional Energy Transfer Cost",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(#A, #B)",
     "targetFull": "divideSeries(movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.costs.*.*))), 86400), 200), movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 200))"
    }
   ]
  },
  {
   "title": "Outgoing Energy Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), '24hour'), 86000)), 0)"
    }
   ]
  },
  {
   "title": "Outgoing Energy per 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), 500), 86000), 0)"
    }
   ]
  },
  { "title": "Room RCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "RCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2.4, "x": 0, "y": 60 },
   "repeat": "colonies",
   "format": "percent",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "asPercent(screeps.$User.colonies.$colonies.rcl.progress, #B)",
     "targetFull": "asPercent(screeps.$User.colonies.$colonies.rcl.progress, screeps.$User.colonies.$colonies.rcl.progressTotal)"
    }
   ]
  },
  { "title": "Custom/Test Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "RCL Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "format": "percent",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(screeps.$User.colonies.$colonies.rcl.progress, 3), '(.*)', 'Progress - \\1')"
    },
    {
     "target": "aliasSub(aliasByNode(screeps.$User.colonies.$colonies.rcl.progressTotal, 3), '(.*)', 'Total - \\1')"
    }
   ]
  },
  {
   "title": "Room CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(screeps.$User.cpu.usage.$colonies.init, 4), '(.*)', 'Init - \\1')"
    },
    {
     "target": "aliasSub(aliasByNode(screeps.$User.cpu.usage.$colonies.run, 4), '(.*)', 'Run - \\1')"
    },
    {
     "target": "aliasSub(aliasByNode(screeps.$User.cpu.usage.$colonies.visuals, 4), '(.*)', 'Visuals - \\1')"
    }
   ]
  }
 ]
}